[files]
# File for storing authentication tokens
tokens = "mit_dk_tokens.json"

[mitid]
# Your MitID username
username = ""

[email]
[email.server]
# Your mail server hostname, e.g. host.server.dk
host = ""
# Mail server port, e.g. 465
port = ""

[email.credentials]
# Sender mail account username
username = ""
# Sender mail account password
password = ""

[email.options]
# Sender e-mail, e.g. trump@usa.gov
from = ""
# Recipient e-mail, e.g. hillary@clinton.net
to = ""
